// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfMSlHfHVwSDtuPaNwbMnFZlaVQtuhvw8',
    appId: '1:301743156631:web:fd71d097df3f94d592a8d2',
    messagingSenderId: '301743156631',
    projectId: 'smartfit-c05df',
    authDomain: 'smartfit-c05df.firebaseapp.com',
    storageBucket: 'smartfit-c05df.appspot.com',
    measurementId: 'G-GP0ZQYJ0QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLHxx2h7_lSWDBdQ45QLF9aFGts7Ug0oU',
    appId: '1:301743156631:android:4ae520b40fffc63192a8d2',
    messagingSenderId: '301743156631',
    projectId: 'smartfit-c05df',
    storageBucket: 'smartfit-c05df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKRpBGslhe8sBWZxo5VXkIJREeZpN_HHI',
    appId: '1:301743156631:ios:5b8ef4732ecb34af92a8d2',
    messagingSenderId: '301743156631',
    projectId: 'smartfit-c05df',
    storageBucket: 'smartfit-c05df.appspot.com',
    iosClientId: '301743156631-hpc67ml8286mjb4ofk1hf3ei4h4tvo2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartfit3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKRpBGslhe8sBWZxo5VXkIJREeZpN_HHI',
    appId: '1:301743156631:ios:f564d69436071f2392a8d2',
    messagingSenderId: '301743156631',
    projectId: 'smartfit-c05df',
    storageBucket: 'smartfit-c05df.appspot.com',
    iosClientId: '301743156631-j1ks9cnhlr750hhqov55rcak2j02p8g5.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartfit3.RunnerTests',
  );
}
